- name: Instalacion de Google Chrome
  hosts: virtualmachine
  gather_facts: true
  become_user: root
  tasks:
     - name: Adding repository for Google Chrome for Linux
       apt_repository:
         repo: deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main
         state: present
         filename: google-chrome

     - name: Import Google Chrome GPG key
       apt_key:
         url: https://dl.google.com/linux/linux_signing_key.pub
         state: present

     - name: Update Cache
       apt:
         update_cache: yes

     - name: Install Google Chrome
       apt:
         name: google-chrome-stable
         state: present

